[GNSS-SDR]

GNSS-SDR.internal_fs_sps=25000000

SignalSource.implementation=File_Signal_Source
SignalSource.filename=data/cleanStatic_snippet.bin
SignalSource.item_type=ishort
SignalSource.sampling_frequency=25000000
SignalSource.samples=0
SignalSource.repeat=false

SignalConditioner.implementation=Signal_Conditioner
DataTypeAdapter.implementation=Ishort_To_Complex
InputFilter.implementation=Pass_Through
Resampler.implementation=Pass_Through

Channels_1C.count=8
Channel.signal=1C

Acquisition_1C.implementation=GPS_L1_CA_PCPS_Acquisition
Acquisition_1C.threshold=2.5

Tracking_1C.implementation=GPS_L1_CA_DLL_PLL_Tracking
Tracking_1C.dump=true
Tracking_1C.dump_filename=data/output/tracking_ch_

TelemetryDecoder_1C.implementation=GPS_L1_CA_Telemetry_Decoder

Observables.implementation=Hybrid_Observables
Observables.dump=true
Observables.dump_filename=data/output/observables.dat

PVT.implementation=RTKLIB_PVT
PVT.output_rate_ms=1000
PVT.dump=true
PVT.dump_filename=data/output/pvt.txt